description: Get repository last release

inputs:
  repo:
    description: Repository
    default: ${{ github.repository }}
    required: false
  token:
    description: Auth token
    default: ${{ github.token }}
    required: false
  domain:
    description: Service domain name
    default: github.com
    required: false
  scheme:
    description: Service scheme
    default: https
    required: false

outputs:
  id:
    description: Id of the release
    value: ${{ steps.gl-info.outputs.id || steps.gh-info.outputs.id }}
  name:
    description: Name of the release
    value: ${{ steps.gl-info.outputs.name || steps.gh-info.outputs.name }}
  tag:
    description: Tag of the release
    value: ${{ steps.gl-info.outputs.tag || steps.gh-info.outputs.tag }}
  created_at:
    description: Creation date of the release
    value: ${{ steps.gl-info.outputs.created_at || steps.gh-info.outputs.created_at }}
  draft:
    description: Release is draft
    value: ${{ steps.gl-info.outputs.draft || steps.gh-info.outputs.draft }}
  prerelease:
    description: Release is prerelease
    value: ${{ steps.gl-info.outputs.prerelease || steps.gh-info.outputs.prerelease }}
  release:
    description: Release is production release
    value: ${{ steps.gl-info.outputs.release || steps.gh-info.outputs.release }}
  url:
    description: API URL to release
    value: ${{ steps.gl-info.outputs.url || steps.gh-info.outputs.url }}
  html_url:
    description: HTML URL to release
    value: ${{ steps.gl-info.outputs.html_url || steps.gh-info.outputs.html_url }}

runs:
  using: composite
  steps:
    - name: Get github repo info
      id: gh-info
      shell: bash
#      if: inputs.domain == 'github.com' || inputs.domain == 'api.github.com'
      run: |
        repo="${{ inputs.repo || github.repository }}"
        url="https://api.github.com/repos/$repo/releases/latest"
        result=`curl --compressed -sL --no-progress-bar \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            "$url"`
        for i in id name created_at draft prerelease url html_url; do
          echo -n "$i=" >> $GITHUB_OUTPUT
          echo "$result" | jq ".$i // \"\"" >> $GITHUB_OUTPUT
          echo -n "$i="
          echo "$result" | jq ".$i // \"\""
        done
        echo -n "tag=" >> $GITHUB_OUTPUT
        echo "$result" | jq ".tag_name // \"\"" >> $GITHUB_OUTPUT

        echo -n "tag="
        echo "$result" | jq ".tag_name"' // ""'

        echo "suka=suka" >> $GITHUB_OUTPUT
        echo "suka2=suka2" >> "$GITHUB_OUTPUT"

#    - name: Get gitlab repo info
##      id: gl-info
#      shell: bash
#      if: inputs.domain != 'github.com' && inputs.domain != 'api.github.com' && inputs.repo
#      run: |
#        repo="${{ inputs.repo }}"
#        site="${{ inputs.scheme }}://${{ inputs.domain }}"
#        url="$site/$repo/-/releases?format=json"
#        token="${{ inputs.token != github.token && inputs.token || '' }}"
#        if test -n "$token"; then
#          auth_header="-H 'Authorization: Bearer $token'"
#        fi
#        echo "curl --compressed -sL --no-progress-bar -H 'Accept: application/vnd.github+json' $auth_header '$url'"
#        result=`curl --compressed -sL --no-progress-bar \
#          -H "Accept: application/vnd.github+json" $auth_header "$url"`
#        for i in id name tag created_at; do
#          echo -n "$i=" >> $GITHUB_OUTPUT
#          echo "$result" | jq ".$i"' // ""' >> $GITHUB_OUTPUT
#          echo -n "$i="
#          echo "$result" | jq ".$i"' // ""'
#        done
#        echo "puka=suka" >> $GITHUB_OUTPUT
#        echo "puka2=suka2" >> "$GITHUB_OUTPUT"
