description: Get repository last release

inputs:
  repo:
    description: Repository
    default: ${{ github.repository }}
    required: false
  token:
    description: Auth token
    default: ${{ github.token }}
    required: false
  saveto:
    description: Var name to save to
    default: release_id
    required: false

outputs:
  id:
    description: Id of the release
  name:
    description: Name of the release
  tag_name:
    description: Tag of the release
  created_at:
    description: Creation date of the release
  draft:
    description: Release is draft
  prerelease:
    description: Release is prerelease
  release:
    description: Release is production release
  url:
    description: API URL to release
  html_url:
    description: HTML URL to release

runs:
  using: composite
  steps:
    - name: Get external repo info
      shell: bash
      run: |
        result=`curl -sL --no-progress-bar \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repo || github.repository }}/releases/latest"`
        for i in id name tag_name created_at draft prerelease url html_url; do
          echo -n "$i=" >> "$GITHUB_OUTPUT"
          echo "$result" | jq ".$i"' // ""' >> "$GITHUB_OUTPUT"

          echo -n "$i="
          echo "$result" | jq ".$i"' // ""'
        done
