description: Get repository last release

inputs:
  repo:
    description: Repository
    default: ${{ github.repository }}
    required: false
  token:
    description: Auth token
    default: ${{ github.token }}
    required: false
  saveto:
    description: Var name to save to
    default: release_id
    required: false

runs:
  using: composite
  steps:
    - name: Get self repo info
      id: self
      if: inputs.repo == github.repository
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ inputs.token }}
        exclude_types: release
        view_top: 1

    - name: Print result
      if: inputs.repo == github.repository
      run: |
        test -z "${{ steps.self.outputs.id }}" || echo "${{ inputs.saveto }}=${{ steps.self.outputs.id }}" >> $GITHUB_ENV
        echo "${{ inputs.saveto }}=${{ steps.self.outputs.id }}"

    - name: Get external repo info
      if: inputs.repo != github.repository
      shell: bash
      run: |
        result=`curl -sL --no-progress-bar \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repo }}/releases/latest" | jq .id`
        test -z "${result}" || echo "${{ inputs.saveto }}=${result}" >> $GITHUB_ENV
        echo "${{ inputs.saveto }}=${result}"
